### ISSUE TITLE
This is not an issue just a help

### ISSUE THREAD

**Issue by shootdot** [harrego/yt-scraper#11]
Hi 
Can u give an example how to use the options area in the module I tried a lot but couldn't get any :( 
Pls Help

**Comment by harrego** [comment]
No problem, as a baseline the following code will get info on a video by returning a video object (documented on the front page README):
```
const ytScraper = require("yt-scraper")
ytScraper.videoInfo("https://www.youtube.com/watch?v=FNkntZMzE9o")
.then(video => {
    console.log("video title is: " + video.title)
})
```

In most cases you don't need to provide any options since they're only present for rare edge cases (e.g. trying to keep requests low by not scraping the parent channel or manually parsing the raw YouTube data). But for example if you want to provide an option to bypass the video ID check, you would provide `{ "bypassIdCheck": true }` after the video URL. It would look like this:

```
ytScraper.videoInfo("https://www.youtube.com/watch?v=FNkntZMzE9o", { "bypassIdCheck": true })
.then(video => {
    console.log("video title is: " + video.title)
})
```

Let me know how it goes :-)

**Comment by shootdot** [comment]
Thanks alot dude

**Comment by shootdot** [comment]
Hi again,
Is there anyway to get channel author ?

**Comment by harrego** [comment]
Yes, a video object (`video` in above example) contains a `channel` key with tons of channel info. Take a look at the "Channel object" table on the front page README for the all the available info.
